# Déploie une app Node.js sur Azure App Service
# Docs : https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - azure-backend-isonic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D66E4A0541AF431A8E0ED1D8E9DC1CB3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7CD0BA8AE4DB41349D9BEFC4868F7629 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_483E4591C51D4D039DBC82D123C57FFA }}

      - name: Deploy dist to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'azure-backend-isonic'
          slot-name: 'Production'
          package: dist
